import Head from "next/head";
import { ReactElement, ReactNode } from "react";
import Sidebar from "../components/sidebar/Sidebar";
import Header from "./Header";

type LayoutProps = {
  children: ReactElement | ReactNode;
};

export default function Layout(props: LayoutProps) {
  return (
    <div>
      <Head>
        <title>Youtube Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />
      <main className="ml-respect-sidebar relative">{props.children}</main>
    </div>
  );
}
